/* Generated By:JavaCC: Do not edit this line. SMIParserConstants.java */
package pt.ipb.marser.smi;

public interface SMIParserConstants {

  int EOF = 0;
  int OBJECT_IDENTIFIER_TKN = 8;
  int OCTET_STRING_TKN = 9;
  int BSTRING_TKN = 10;
  int HSTRING_TKN = 11;
  int CSTRING_TKN = 12;
  int NUMBER_ERANGE_TKN = 13;
  int NUMBER_TKN = 14;
  int DOT_TKN = 15;
  int COMMA_TKN = 16;
  int LEFTBRACE_TKN = 17;
  int RIGHTBRACE_TKN = 18;
  int LEFTPAREN_TKN = 19;
  int RIGHTPAREN_TKN = 20;
  int LEFTBRACKET_TKN = 21;
  int RIGHTBRACKET_TKN = 22;
  int LESSTHAN_TKN = 23;
  int MINUS_TKN = 24;
  int GETS_TKN = 25;
  int BAR_TKN = 26;
  int SEMI_COLON_TKN = 27;
  int SELECTOR_TKN = 28;
  int INTEGER32_TKN = 29;
  int INTEGER_TKN = 30;
  int BITS_TKN = 31;
  int IPADDRESS_TKN = 32;
  int COUNTER32_TKN = 33;
  int GAUGE32_TKN = 34;
  int TIMETICKS_TKN = 35;
  int OPAQUE_TKN = 36;
  int COUNTER64_TKN = 37;
  int UNSIGNED32_TKN = 38;
  int SEQUENCE_TKN = 39;
  int OF_TKN = 40;
  int SIZE_TKN = 41;
  int BEGIN_TKN = 42;
  int END_TKN = 43;
  int DEFINITIONS_TKN = 44;
  int IMPORTS_TKN = 45;
  int FROM_TKN = 46;
  int EXPORTS_TKN = 47;
  int OBJECT_TYPE_TKN = 48;
  int SYNTAX_TKN = 49;
  int STATUS_TKN = 50;
  int DESCRIPTION_TKN = 51;
  int REFERENCE_TKN = 52;
  int INDEX_TKN = 53;
  int DEFVAL_TKN = 54;
  int DHINT_TKN = 55;
  int IMPLIED_TKN = 56;
  int TC_TKN = 57;
  int MODULE_TKN = 58;
  int MANDATORY_GROUPS_TKN = 59;
  int GROUP_TKN = 60;
  int OBJECT_TKN = 61;
  int WRITE_SYNTAX_TKN = 62;
  int OBJECTS_TKN = 63;
  int AUGMENTS_TKN = 64;
  int MODULE_IDENTITY_TKN = 65;
  int LAST_UPDATED_TKN = 66;
  int ORGANIZATION_TKN = 67;
  int CONTACT_INFO_TKN = 68;
  int REVISION_TKN = 69;
  int NOTIFICATION_TYPE_TKN = 70;
  int OBJECT_IDENTITY_TKN = 71;
  int MAX_ACCESS_TKN = 72;
  int MIN_ACCESS_TKN = 73;
  int UNITS_TKN = 74;
  int TRAP_TYPE_TKN = 75;
  int ENTERPRISE_TKN = 76;
  int VARIABLES_TKN = 77;
  int ACCESS_TKN = 78;
  int CHOICE_TKN = 79;
  int IMPLICIT_TKN = 80;
  int APPLICATION_TKN = 81;
  int OBJECT_GROUP_TKN = 82;
  int NOTIFICATION_GROUP_TKN = 83;
  int NOTIFICATIONS_TKN = 84;
  int MODULE_COMPLIANCE_TKN = 85;
  int AGENT_CAPABILITIES_TKN = 86;
  int MACRO_TKN = 87;
  int LCASEFIRST_IDENT_TKN = 88;
  int UCASEFIRST_IDENT_TKN = 89;

  int DEFAULT = 0;
  int WithinASNComment = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"--\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<OBJECT_IDENTIFIER_TKN>",
    "<OCTET_STRING_TKN>",
    "<BSTRING_TKN>",
    "<HSTRING_TKN>",
    "<CSTRING_TKN>",
    "<NUMBER_ERANGE_TKN>",
    "\"0\"",
    "\".\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"<\"",
    "\"-\"",
    "\"::=\"",
    "\"|\"",
    "\";\"",
    "\":\"",
    "\"Integer32\"",
    "\"INTEGER\"",
    "\"BITS\"",
    "\"IpAddress\"",
    "\"Counter32\"",
    "\"Gauge32\"",
    "\"TimeTicks\"",
    "\"Opaque\"",
    "\"Counter64\"",
    "\"Unsigned32\"",
    "\"SEQUENCE\"",
    "\"OF\"",
    "\"SIZE\"",
    "\"BEGIN\"",
    "\"END\"",
    "\"DEFINITIONS\"",
    "\"IMPORTS\"",
    "\"FROM\"",
    "\"EXPORTS\"",
    "\"OBJECT-TYPE\"",
    "\"SYNTAX\"",
    "\"STATUS\"",
    "\"DESCRIPTION\"",
    "\"REFERENCE\"",
    "\"INDEX\"",
    "\"DEFVAL\"",
    "\"DISPLAY-HINT\"",
    "\"IMPLIED\"",
    "\"TEXTUAL-CONVENTION\"",
    "\"MODULE\"",
    "\"MANDATORY-GROUPS\"",
    "\"GROUP\"",
    "\"OBJECT\"",
    "\"WRITE-SYNTAX\"",
    "\"OBJECTS\"",
    "\"AUGMENTS\"",
    "\"MODULE-IDENTITY\"",
    "\"LAST-UPDATED\"",
    "\"ORGANIZATION\"",
    "\"CONTACT-INFO\"",
    "\"REVISION\"",
    "\"NOTIFICATION-TYPE\"",
    "\"OBJECT-IDENTITY\"",
    "\"MAX-ACCESS\"",
    "\"MIN-ACCESS\"",
    "\"UNITS\"",
    "\"TRAP-TYPE\"",
    "\"ENTERPRISE\"",
    "\"VARIABLES\"",
    "\"ACCESS\"",
    "\"CHOICE\"",
    "\"IMPLICIT\"",
    "\"APPLICATION\"",
    "\"OBJECT-GROUP\"",
    "\"NOTIFICATION-GROUP\"",
    "\"NOTIFICATIONS\"",
    "\"MODULE-COMPLIANCE\"",
    "\"AGENT-CAPABILITIES\"",
    "\"MACRO\"",
    "<LCASEFIRST_IDENT_TKN>",
    "<UCASEFIRST_IDENT_TKN>",
  };

}
